language: php

php:
    - 7.0
    - 7.1
    - hhvm
    
matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer install

script:
  - bin/phpspec run --format pretty
  
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml

